/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_capping_xinran_jnitest_JNIUtils */

#ifndef _Included_com_capping_xinran_jnitest_JNIUtils
#define _Included_com_capping_xinran_jnitest_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_capping_xinran_jnitest_JNIUtils
 * Method:    getStringFormC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_capping_xinran_jnitest_JNIUtils_getStringFormC
  (JNIEnv *, jclass);

/*
 * Class:     com_capping_xinran_jnitest_JNIUtils
 * Method:    getKeyValue
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_capping_xinran_jnitest_JNIUtils_getKeyValue
  (JNIEnv *, jclass);

/*
 * Class:     com_capping_xinran_jnitest_JNIUtils
 * Method:    getIv
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_capping_xinran_jnitest_JNIUtils_getIv
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
